name: impaktfull_ui
description: "A new Flutter package project."
version: 0.12.0
publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.4
  flutter_svg: ^2.0.10+1
  impaktfull_ui_figma_sync:
    git:
      url: https://github.com/impaktfull/flutter_impaktfull_ui_figma_sync.git
      ref: '1ef5858'
  intl: ^0.19.0
  lottie: ^3.0.0
  phosphor_flutter: ^2.1.0
  rive: ^0.13.14
  snacky: ^0.5.3

dev_dependencies:
  alchemist: ^0.10.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
