name: impaktfull_ui
description: impaktfull ui components to simplify development and design
  processes while still allowing custom design
version: 0.80.0
repository: https://github.com/impaktfull/flutter_impaktfull_ui
environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=3.44.0"
dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.3.5
  flutter_markdown_plus: ^1.0.7
  flutter_svg: ^2.3.0
  impaktfull_ui_figma_sync: ^0.0.2
  intl: ^0.20.2
  lottie: ^3.3.3
  markdown: ^7.3.1
  phosphoricons_flutter: ^1.0.0
  rive: ^0.14.8
  snacky: ^0.8.0
  web: ^1.1.1
dev_dependencies:
  alchemist: ^0.14.0
  flutter_lints: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
