name: impaktfull_ui_2
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.4
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  lottie: ^3.0.0
  phosphor_flutter: ^2.1.0
  rive: ^0.13.14
  snacky: ^0.5.3

dev_dependencies:
  alchemist: ^0.10.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
