name: impaktfull_ui_2
description: "A new Flutter package project."
version: 0.0.6
homepage:

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.19.0
  flutter:
    sdk: flutter
  lottie: ^3.0.0
  snacky: ^0.2.4
  phosphor_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/icons/
    - assets/lottie/
