import 'package:impaktfull_ui_example/src/component_library/items/accordion/accordion_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/adaptive_nav_bar/adaptive_nav_bar_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/adaptive_screen/adaptive_screen_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/asset/asset_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/auto_complete/auto_complete_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/autolayout/autolayout_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/avatar/avatar_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/badge/badge_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/bottom_navigation/bottom_navigation_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/bottom_navigation_item/bottom_navigation_item_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/bottomsheet/bottomsheet_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/button/button_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/calendar/calendar_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/card/card_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/carrousel/carrousel_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/chat/chat_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/checkbox/checkbox_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/clamped_fractionally_sized_box/clamped_fractionally_sized_box_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/cms_header/cms_header_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/color_picker/color_picker_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/command_menu/command_menu_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/confetti/confetti_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/date_picker/date_picker_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/date_time_picker/date_time_picker_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/divider/divider_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/dropdown/dropdown_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/file_picker/file_picker_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/floating_action_button/floating_action_button_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/fluid_padding/fluid_padding_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/gallery/gallery_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/grid_view/grid_view_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/horizontal_tabs/horizontal_tabs_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/icon_button/icon_button_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/image_crop/image_crop_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/input_field/input_field_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/introduction/introduction_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/line_chart/line_chart_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/list_item/list_item_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/list_view/list_view_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/loading_error_data/loading_error_data_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/loading_indicator/loading_indicator_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/markdown/markdown_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/master_detail/master_detail_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/metric/metric_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/modal/modal_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/morse_code_touch_feedback/morse_code_touch_feedback_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/nav_bar/nav_bar_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/notification/notification_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/notification_badge/notification_badge_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/number_input/number_input_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/option_selector/option_selector_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/pagination/pagination_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/pin_code/pin_code_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/placeholder_state/placeholder_state_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/progress_indicator/progress_indicator_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/radio_button/radio_button_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/radio_button_list_item/radio_button_list_item_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/refreshindicator/refreshindicator_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/responsive_layout/responsive_layout_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/responsive_row/responsive_row_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/screen/screen_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/section_title/section_title_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/segmented_control/segmented_control_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/selectable_list_item/selectable_list_item_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/separated_column/separated_column_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/sidebar_navigation/sidebar_navigation_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/sidebar_navigation_item/sidebar_navigation_item_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/simple_list_item/simple_list_item_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/skeleton/skeleton_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/slider/slider_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/snacky/snacky_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/stepper/stepper_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/switch/switch_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/switch_list_item/switch_list_item_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/tab_bar/tab_bar_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/table/table_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/time_picker/time_picker_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/tooltip/tooltip_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/touch_feedback_sequence/touch_feedback_sequence_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/virtual_keyboard/virtual_keyboard_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/wrap/wrap_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/items/wysiwyg/wysiwyg_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/config/component_library_item.dart';

class ComponentLibrary {
  static ComponentLibrary? _instance;

  ComponentLibrary._();

  static ComponentLibrary get instance => _instance ??= ComponentLibrary._();

  final List<ComponentLibraryItem> items = [
    const AccordionLibraryItem(),
    const AdaptiveNavBarLibraryItem(),
    const AdaptiveScreenLibraryItem(),
    const AssetLibraryItem(),
    const AutoCompleteLibraryItem(),
    const AutoLayoutLibraryItem(),
    const AvatarLibraryItem(),
    const BadgeLibraryItem(),
    const BottomNavigationItemLibraryItem(),
    const BottomNavigationLibraryItem(),
    const BottomSheetLibraryItem(),
    const ButtonLibraryItem(),
    const CalendarLibraryItem(),
    const CardLibraryItem(),
    const CarrouselLibraryItem(),
    const ChatLibraryItem(),
    const CheckboxLibraryItem(),
    const ClampedFractionallySizedBoxLibraryItem(),
    const CmsHeaderLibraryItem(),
    const ColorPickerLibraryItem(),
    const CommandMenuLibraryItem(),
    const ConfettiLibraryItem(),
    const DatePickerLibraryItem(),
    const DateTimePickerLibraryItem(),
    const DividerLibraryItem(),
    const DropdownLibraryItem(),
    const FilePickerLibraryItem(),
    const FloatingActionButtonLibraryItem(),
    const FluidPaddingLibraryItem(),
    const GalleryLibraryItem(),
    const GridViewLibraryItem(),
    const HorizontalTabsLibraryItem(),
    const IconButtonLibraryItem(),
    const ImageCropLibraryItem(),
    const InputFieldLibraryItem(),
    const IntroductionLibraryItem(),
    const LineChartLibraryItem(),
    const ListItemLibraryItem(),
    const ListViewLibraryItem(),
    const LoadingErrorDataLibraryItem(),
    const LoadingIndicatorLibraryItem(),
    const MarkdownLibraryItem(),
    const MasterDetailLibraryItem(),
    const MetricLibraryItem(),
    const ModalLibraryItem(),
    const MorseCodeTouchFeedbackLibraryItem(),
    const NavBarLibraryItem(),
    const NotificationBadgeLibraryItem(),
    const NotificationLibraryItem(),
    const NumberInputLibraryItem(),
    const OptionSelectorLibraryItem(),
    const PaginationLibraryItem(),
    const PinCodeLibraryItem(),
    const PlaceholderStateLibraryItem(),
    const ProgressIndicatorLibraryItem(),
    const RadioButtonLibraryItem(),
    const RadioButtonListItemLibraryItem(),
    const RefreshIndicatorLibraryItem(),
    const ResponsiveLayoutLibraryItem(),
    const ResponsiveRowLibraryItem(),
    const ScreenLibraryItem(),
    const SectionTitleLibraryItem(),
    const SegmentedControlLibraryItem(),
    const SelectableListItemLibraryItem(),
    const SeparatedColumnLibraryItem(),
    const SidebarNavigationItemLibraryItem(),
    const SidebarNavigationLibraryItem(),
    const SimpleListItemLibraryItem(),
    const SkeletonLibraryItem(),
    const SliderLibraryItem(),
    const SnackyLibraryItem(),
    const StepperLibraryItem(),
    const SwitchLibraryItem(),
    const SwitchListItemLibraryItem(),
    const TabBarLibraryItem(),
    const TableLibraryItem(),
    const TimePickerLibraryItem(),
    const TooltipLibraryItem(),
    const TouchFeedbackSequenceLibraryItem(),
    const VirtualKeyboardLibraryItem(),
    const WrapLibraryItem(),
    const WysiwygLibraryItem(),
  ];
}
