import 'package:impaktfull_ui_example/src/component_library/components/asset/asset_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/autolayout/autolayout_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/avatar/avatar_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/badge/badge_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/bottom_navigation/bottom_navigation_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/bottom_navigation_item/bottom_navigation_item_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/bottomsheet/bottomsheet_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/button/button_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/card/card_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/checkbox/checkbox_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/cms_header/cms_header_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/color_picker/color_picker_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/command_menu/command_menu_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/date_picker/date_picker_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/divider/divider_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/dropdown/dropdown_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/file_picker/file_picker_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/floating_action_button/floating_action_button_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/fluid_padding/fluid_padding_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/grid_view/grid_view_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/horizontal_tabs/horizontal_tabs_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/icon_button/icon_button_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/input_field/input_field_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/list_item/list_item_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/list_view/list_view_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/loading_error_data/loading_error_data_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/loading_indicator/loading_indicator_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/modal/modal_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/nav_bar/nav_bar_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/notification/notification_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/notification_badge/notification_badge_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/pagination/pagination_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/progress_indicator/progress_indicator_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/radio_button/radio_button_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/radio_button_list_item/radio_button_list_item_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/refreshindicator/refreshindicator_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/screen/screen_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/section_title/section_title_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/selectable_list_item/selectable_list_item_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/separated_column/separated_column_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/sidebar_navigation/sidebar_navigation_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/sidebar_navigation_item/sidebar_navigation_item_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/simple_list_item/simple_list_item_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/snacky/snacky_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/switch/switch_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/switch_list_item/switch_list_item_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/tab_bar/tab_bar_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/table/table_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/components/tooltip/tooltip_library_item.dart';
import 'package:impaktfull_ui_example/src/component_library/config/component_library_item.dart';

class ComponentLibrary {
  final List<ComponentLibraryItem> components = [
    const AssetLibraryItem(),
    const AutoLayoutLibraryItem(),
    const AvatarLibraryItem(),
    const BadgeLibraryItem(),
    const BottomNavigationLibraryItem(),
    const BottomNavigationItemLibraryItem(),
    const BottomSheetLibraryItem(),
    const ButtonLibraryItem(),
    const CheckboxLibraryItem(),
    const CardLibraryItem(),
    const CmsHeaderLibraryItem(),
    const ColorPickerLibraryItem(),
    const CommandMenuLibraryItem(),
    const DatePickerLibraryItem(),
    const DividerLibraryItem(),
    const DropdownLibraryItem(),
    const FilePickerLibraryItem(),
    const FloatingActionButtonLibraryItem(),
    const FluidPaddingLibraryItem(),
    const GridViewLibraryItem(),
    const HorizontalTabsLibraryItem(),
    const InputFieldLibraryItem(),
    const IconButtonLibraryItem(),
    const ListItemLibraryItem(),
    const ListViewLibraryItem(),
    const LoadingErrorDataLibraryItem(),
    const LoadingIndicatorLibraryItem(),
    const ModalLibraryItem(),
    const NavBarLibraryItem(),
    const NotificationLibraryItem(),
    const NotificationBadgeLibraryItem(),
    const PaginationLibraryItem(),
    const ProgressIndicatorLibraryItem(),
    const RadioButtonLibraryItem(),
    const RadioButtonListItemLibraryItem(),
    const RefreshIndicatorLibraryItem(),
    const ScreenLibraryItem(),
    const SectionTitleLibraryItem(),
    const SelectableListItemLibraryItem(),
    const SeparatedColumnLibraryItem(),
    const SidebarNavigationLibraryItem(),
    const SidebarNavigationItemLibraryItem(),
    const SimpleListItemLibraryItem(),
    const SnackyLibraryItem(),
    const SwitchLibraryItem(),
    const SwitchListItemLibraryItem(),
    const TabBarLibraryItem(),
    const TableLibraryItem(),
    const TooltipLibraryItem(),
  ];
}
