name: Publish to github pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate SSH Key
        run: |
          ssh-keygen -t rsa -b 4096 -C "github-actions" -f /tmp/github_actions_key -N ""
          eval "$(ssh-agent -s)"
          ssh-add /tmp/github_actions_key
      - name: Add GitHub to Known Hosts
        run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter packages get
      - run: dart analyze
      - run: flutter packages get
        working-directory: ./example
      - run: dart analyze
        working-directory: ./example
      - run: flutter build web
        working-directory: ./example
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./example/build/web"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
