name: Automated tests

on:
  push:
    branches:
      - main
jobs:
  test:
    name: Runs all tests on main
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter test
